services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - NODE_VERSION=${NODE_VERSION}
    ports:
      - "${PORT}:5173"
    volumes:
      - ${PROJECTS_ROOT}:/app